### ISSUE TITLE
Log Problem

### ISSUE THREAD

**Issue by mertbuldur** [PatrissolJuns/react-native-audio-video-tools#1]
hi why is the log output like this?
![Ekran Resmi 2020-12-12 20 48 29](https://user-images.githubusercontent.com/8089725/101991099-75552f80-3cbb-11eb-8e65-1e26e7fd8a9a.png)

**Comment by mertbuldur** [comment]
sorry, this package not working  :/ 
![Ekran Resmi 2020-12-12 21 08 10](https://user-images.githubusercontent.com/8089725/101991510-38d70300-3cbe-11eb-824a-557620c262e7.png)

**Comment by PatrissolJuns** [comment]
Hello @mertbuldur, how did you do to get this result? What did you want to do? Have you tried the Example project because the package works perfectly!

**Comment by mertbuldur** [comment]
hello i use  this code `const videoTools = new VideoTools("http://techslides.com/demos/sample-videos/small.mp4");

// Get details about the video
videoTools.getDetails().then(details => {
    console.log("Size: " + details.size);
    console.log("Duration: " + details.duration);
    // Etc.
});`

but return 
![Ekran Resmi 2020-12-12 21 08 10](https://user-images.githubusercontent.com/8089725/101993062-940df300-3cc8-11eb-8a4e-ce00cacd480a.png)
this error :/

i use ffmpeg  "react-native-ffmpeg": "^0.5.0" If I don't include this version, ffmpeg cannot be found.
Can you update the package for this version?

**Comment by PatrissolJuns** [comment]
> hello i use this code `const videoTools = new VideoTools("http://techslides.com/demos/sample-videos/small.mp4");
> 
> // Get details about the video
> videoTools.getDetails().then(details => {
> console.log("Size: " + details.size);
> console.log("Duration: " + details.duration);
> // Etc.
> });`
> 
> but return
> ![Ekran Resmi 2020-12-12 21 08 10](https://user-images.githubusercontent.com/8089725/101993062-940df300-3cc8-11eb-8a4e-ce00cacd480a.png)
> this error :/
> 
> i use ffmpeg "react-native-ffmpeg": "^0.5.0" If I don't include this version, ffmpeg cannot be found.
> Can you update the package for this version?

Actually, this package requires react-native-ffmpeg, so make sure you have well installed it and well configured it especially check the package under react-native-ffmpeg you have used. For more details, have a look at [https://github.com/tanersener/react-native-ffmpeg#23-packages](https://github.com/tanersener/react-native-ffmpeg#23-packages)
