### ISSUE TITLE
is posible to replace video audio track?

### ISSUE THREAD

**Issue by carlosen14** [PatrissolJuns/react-native-audio-video-tools#12]

**Comment by PatrissolJuns** [comment]
@carlosen14 what do you mean by that ? Can you please give more details on what you want to achieve and what is currently blocking you

**Comment by carlosen14** [comment]
Hi, i was asking abor replace the audio track on a video file.. but i did a bit more of research, and i found out ffmpeg libs (also i was looking for some video efects like instagram, and i will achieve with this).. i am going on that way (even the app will have a huge bundle size).

Thanks for your time..
________________________________
