### ISSUE TITLE
Extract audio

### ISSUE THREAD

**Issue by pwliuab** [PatrissolJuns/react-native-audio-video-tools#9]
![image](https://user-images.githubusercontent.com/67176560/168244611-28b8edec-1e77-4e71-87b0-44c20aa25eb5.png)

When I tried Video.extractAudio(),![image](https://user-images.githubusercontent.com/67176560/168245107-7b07b11c-bdab-4d0b-9008-573871ce7c19.png), the error above showed.

That's because of the existing bugs in "isMediaExtensionCorrect" function in util file, 
since the function compares "video" with mp3 file format, which returns false and throw error.

**Comment by PatrissolJuns** [comment]
Ah I see, so there are videos with mp3 extension ?

**Comment by pwliuab** [comment]
I mean, when video tool object calls "extractAudio", it will check checkInputAndOptions right ?
（file : \node_modules\react-native-audio-video-tools\src\video\index.js, function :  extractAudio)
![image](https://user-images.githubusercontent.com/67176560/168264127-94fbb951-fd09-4db9-b963-8b273d68c1af.png)

then,  since audio is mp3 format, and video object is a video media type, it will return false and throw an error here
(file \node_modules\react-native-audio-video-tools\src\util.js , function:  isOptionsValueCorrect) 
![image](https://user-images.githubusercontent.com/67176560/168264261-a3fc51ef-b402-4932-969c-dfc7a5d87d9f.png)

how I fix the issue is to add a condition here:
(file \node_modules\react-native-audio-video-tools\src\util.js , function:  isOptionsValueCorrect) 
![image](https://user-images.githubusercontent.com/67176560/168264527-2bdbbfd3-91df-4bb3-a349-a2580befa226.png)

when the operation is audio extraction, we should check whether the input options is audio type instead of checking whether they are "Video" type, which will definitely give a false.

**Comment by pwliuab** [comment]
seems like in the original version, it will compare "video === audio", return false, but our purpose in extractAudio is to convert mp4 -> mp3, so mp3 format should compare with "audio format" instead of video format

**Comment by PatrissolJuns** [comment]
yes you seem right. Can you send a pull request ?

**Comment by pwliuab** [comment]
sure, I will send it as soon as possible. ,, my assignment deadline coming soon...

**Comment by pwliuab** [comment]
Have made a pull req. Thx

**Comment by PatrissolJuns** [comment]
Close this issue because a fix [PR](https://github.com/PatrissolJuns/react-native-audio-video-tools/pull/11) has been submitted and merged
